#!/bin/bash

echo "nameserver 200.204.135.203
nameserver 200.204.135.253
nameserver 208.67.222.222
nameserver 208.67.220.220" >> etc/resolv.conf
wget https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2018.1_all.deb && chmod +x kali-* && apt install ./kali-archive-keyring_2018.1_all.deb && echo 'apt::sandbox::seccomp "false";' > /etc/apt/apt.conf.d/999seccomp
apt-get update && apt-get -y upgrade && apt-get -y autoremove && apt-get autoclean
apt-get install -y unzip axel
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip -O ngrok.zip
unzip -o ngrok.zip && cp ngrok /bin && chmod +x /bin/ngrok && rm -rf /root/ngrok*
apt-get install -y metasploit-framework