#!/data/data/com.termux/files/usr/bin/bash -e
clear
menu()
{
clear
echo -e "\n\e[93m@NoobFoda2\n"
echo -e "\n\e[91m1- Instalar kali-minimal"
echo -e "\e[96m2- instala OpenSsh"
echo -e "\e[92m3- Sair"
echo -e -n "\e[92m \n >>>  "
read res
case $res in
"1")
clear
apt-get update && apt-get -y upgrade && apt-get install -y wget git tar proot axel unzip
clear
echo -e "\n\e[93mBaixando o kali-minimal..."
axel -a https://build.nethunter.com/kalifs/release/kalifs-armhf-minimal.tar.xz
echo -e "\n\n\e[94mExtraindo.... \e[92mTempo de extracao 5 a 10 minutos.."
proot --link2symlink tar -xf kalifs-armhf-minimal.tar.xz 2> /dev/null
mv kali-armhf /$HOME
cp dragao /$HOME/kali-armhf/root && cp bash.bashrc /$HOME/kali-armhf/etc && cp kali2 /$HOME/kali-armhf/root
rm kalifs-armhf-minimal.tar.xz
clear
echo -e "\e[94mCriando a sessao de login do kali.."
echo "
#!/data/data/com.termux/files/usr/bin/bash -e
unset LD_PRELOAD
exec proot --link2symlink -0 -r /data/data/com.termux/files/home/kali-armhf -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM="xterm-256color" LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login" >> $PREFIX/bin/startkali
chmod 777 $PREFIX/bin/startkali
sleep 2
echo -e "\n\n\e[94mConcluido pra inicia o kali digite \e[96mstartkali"
echo -e "\n\e[92mVolta para menu-inicial s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saindo.."
exit 
fi
;;
"2")
clear
echo -e "\n\e[93m@NoobFoda2\n"
apt-get update && apt-get -y upgrade && apt-get install -y openssh
echo -e "\n\e[91m Aceite a permissao de acesso ao armazenamento\n"
termux-setup-storage && sleep 2
echo -e "\n\e[94m O serviço agora esta sendo iniciado na porta 8022 voce pode digitar :\e[92m logcat -s 'syslog:*' \e[94m para visualizar a saida de log.\e[93m\n"
sshd
touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh
ssh-keygen
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
cp ~/.ssh/id_rsa /sdcard
echo -e "\n\e[96m Instalacao feita com sucesso! 
 Ex: ssh 127.0.0.1 -p 8022 ou ssh user@127.0.0.1 -p 8022"
echo -e "\e[92mVolta para menu-inicial s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saindo.."
exit 
fi
;;
"3")
if [ "$res" = "5" ]; then
exit
fi
;;
esac
}
menu
